#pragma once

#define EXTRA_SHORT_COMBOS
#define TAPPING_TERM 220
#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define COMBO_TERM 35
#define COMBO_TERM_PER_COMBO
#define COMBO_TERM_RELAXED 50
#define COMBO_TERM_TIGHT 20
#define MK_COMBINED
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MOVE_DELTA 5
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_TIME_TO_MAX 40
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_INTERVAL 50
#define MOUSEKEY_WHEEL_MAX_SPEED 5
#define MOUSEKEY_WHEEL_TIME_TO_MAX 100
#define UNICODE_SELECTED_MODES UNICODE_MODE_MACOS, UNICODE_MODE_LINUX
