#pragma once

#define EXTRA_SHORT_COMBOS
#define TAPPING_TERM 250
#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define COMBO_TERM 35
#define COMBO_TERM_PER_COMBO
#define MK_COMBINED
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 4
#define MOUSEKEY_TIME_TO_MAX 0
#define SELECT_WORD_OS_MAC

#define RGBLIGHT_LED_COUNT 1
#define RGBLIGHT_LIMIT_VAL 1
#define RGBLIGHT_SLEEP
#define RGBLIGHT_LAYERS
